package presenters;

public enum Event {
	PRESS_START_GAME, PRESS_LOAD_GAME, PRESS_EXIT_GAME, PRESS_CONTINUE_GAME, PRESS_RESTART_GAME,
	PRESS_BACK_TO_MENU_GAME, PRESS_SHOW_SCREENS_GAME, PRESS_EXIT_TO_MENU, PRESS_CONFIRM_EXIT_GAME, PRESS_CANCEL_CONFIRM_EXIT_GAME;
}
